// this file was generated by copilot and reviewed by a human

import { cleanup } from "@testing-library/react-native";

// Reset Firebase mocks
import { __resetAuthMock } from "../__mocks__/firebase/auth";
import { __resetFirestoreMock } from "../__mocks__/firebase/firestore";

// Reset AsyncStorage mock
import AsyncStorage from "../__mocks__/@react-native-async-storage/async-storage";

// Reset Image Picker mock
import { __resetImagePickerMock } from "../__mocks__/expo-image-picker";

// Reset navigation mock (TODO)
import { __resetNavigationMock } from "../__mocks__/navigation";

// Run cleanup after each test
afterEach(() => {
  cleanup();

  // Reset all mocks
  __resetAuthMock();
  __resetFirestoreMock();
  AsyncStorage.__reset();
  __resetImagePickerMock();
  __resetNavigationMock();
});

// Fix React Native timers
jest.useFakeTimers();

// Silence React Native warnings that break tests
jest.spyOn(global.console, "warn").mockImplementation(() => {});
jest.spyOn(global.console, "error").mockImplementation(() => {});
