// this file was generated by copilot and reviewed by a human

module.exports = {
  preset: "jest-expo",
  roots: [
    "<rootDir>/../tests",
    "<rootDir>"
  ],
  setupFilesAfterEnv: [
    "<rootDir>/jest.setup.js"
  ],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "babel-jest"
  },
  moduleFileExtensions: [
    "ts",
    "tsx",
    "js",
    "jsx",
    "json",
    "node"
  ],
  moduleNameMapper: {
    // Firebase v9 modular mocks
    "^firebase/auth$": "<rootDir>/../__mocks__/firebase/auth.ts",
    "^firebase/firestore$": "<rootDir>/../__mocks__/firebase/firestore.ts",

    // Native module mocks
    "^@react-native-async-storage/async-storage$":
      "<rootDir>/../__mocks__/@react-native-async-storage/async-storage.ts",
    "^expo-image-picker$":
      "<rootDir>/../__mocks__/expo-image-picker.ts",

    // Navigation mock (for page/tab hook)
    "^@navigation$": "<rootDir>/../__mocks__/navigation.ts",

    // Path alias support
    "^@/(.*)$": "<rootDir>/$1"
  },

  transformIgnorePatterns: [
    "node_modules/(?!(@react-native|react-native|expo|expo-.*|@expo|firebase)/)"
  ],

  // Makes snapshot testing stable even with auto-generated Firestore IDs
  snapshotSerializers: [
    "<rootDir>/../tests/serialisers/firestoreIdSerialiser.js"
  ],

  // necessary for CI coverage reports
  coverageReporters: ["lcov", "text"],

  // Ensures mocks reset between tests
  resetMocks: true,
  clearMocks: true,
  restoreMocks: true,
};
