// this file was generated by copilot and reviewed by a human

module.exports = {
  preset: "jest-expo",
  roots: [
    "<rootDir>/../tests",
    "<rootDir>"
  ],
  setupFilesAfterEnv: [
    "<rootDir>/jest.setup.js"
  ],
  transform: {
    "^.+\\.(js|jsx|ts|tsx)$": "babel-jest"
  },
  moduleFileExtensions: [
    "ts",
    "tsx",
    "js",
    "jsx",
    "json",
    "node"
  ],
  moduleNameMapper: {
    // Firebase v9 modular mocks
    "^firebase/app$": "<rootDir>/../__mocks__/firebase/app.ts",
    "^firebase/auth$": "<rootDir>/../__mocks__/firebase/auth.ts",
    "^firebase/firestore$": "<rootDir>/../__mocks__/firebase/firestore.ts",

    // Native module mocks
    "^@react-native-async-storage/async-storage$":
      "<rootDir>/../__mocks__/@react-native-async-storage/async-storage.ts",
    "^expo-image-picker$":
      "<rootDir>/../__mocks__/expo-image-picker.ts",

    // Navigation mock (for page/tab hook)
    "^@navigation$": "<rootDir>/../__mocks__/navigation.ts",

    // Path alias support
    "^@/(.*)$": "<rootDir>/$1"
  },

  transformIgnorePatterns: [
    "node_modules/(?!(@react-native|react-native|expo|expo-.*|@expo|firebase)/)"
  ],

  // Makes snapshot testing stable even with auto-generated Firestore IDs
  snapshotSerializers: [
    "<rootDir>/../tests/serialisers/firestoreIdSerialiser.js"
  ],

  // necessary for CI coverage reports
  coverageReporters: ["lcov", "text"],

  // Ensures mocks reset between tests
  //
  // Gotcha: resetMocks strips any jest.fn() implementation (mockReturnValue/mockResolvedValue/
  // mockImplementation, or one passed to jest.fn(impl) directly) before EVERY test, including
  // the first - even one defined inside a jest.mock(...) factory at the top of a test file. If a
  // mocked module needs a default return value but nothing asserts on how it was called, define
  // it as a plain function in the factory instead of jest.fn() so there's no implementation for
  // resetMocks to strip. If you do need call assertions, re-apply the mockImplementation/
  // mockResolvedValue in a beforeEach (it runs after the auto-reset, so it sticks for that test).
  resetMocks: true,
  clearMocks: true,
  restoreMocks: true,
};
