import { StyleSheet } from 'react-native';

export const colors = {
  darkBlue: '#095389',
  mediumBlue: '#1376BE',
  pending: '#FF7052',
  pendingLight: '#FFBEB5',
  awaiting: '#FFA852',
  awaitingLight: '#FFF1A1',
  confirmed: '#37B157',
  confirmedLight: '#B9FFB0',
  white: '#FFFFFF',
};

export default StyleSheet.create({
  // App-specific
  screen: { flex: 1, backgroundColor: colors.darkBlue, justifyContent: 'center', padding: 24 },
  card: { backgroundColor: colors.white, borderRadius: 24, padding: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 16, elevation: 4 },
  title: { fontFamily: 'Marcellus_400Regular', fontSize: 32, color: colors.darkBlue, marginBottom: 8 },
  subtitle: { fontFamily: 'Marcellus_400Regular', fontSize: 16, color: colors.darkBlue, marginBottom: 20 },
  contentContainer: { flex: 1 },
  appContainer: {
    flex: 1,
    backgroundColor: colors.darkBlue,
  },
  pageScreen: {
    flex: 1,
    backgroundColor: colors.darkBlue,
    justifyContent: 'center',
    paddingTop: 40,
    paddingHorizontal: 24,
    paddingBottom: 100,
  },
  pageTitle: {
    fontSize: 38,
    fontWeight: '800',
    color: colors.darkBlue,
    marginBottom: 12,
  },
  pageSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.darkBlue,
  },
  pageCard: {
    flex: 1,
    borderRadius: 28,
    backgroundColor: colors.white,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 6,
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: colors.darkBlue,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    color: colors.white,
    fontSize: 15,
    marginTop: 12,
  },
  input: {
    borderColor: '#cbd5e1',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2563eb',
    borderRadius: 12,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  primaryButtonDisabled: {
    backgroundColor: '#93c5fd',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  helperText: {
    color: '#64748b',
    fontSize: 13,
    marginTop: 12,
    textAlign: 'center',
  },
  editButton: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 12,
  },
  editButtonText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  avatarUploadButton: {
    alignSelf: 'center',
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
    borderRadius: 999,
    borderWidth: 1,
    marginBottom: 14,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  avatarUploadText: {
    color: '#1d4ed8',
    fontWeight: '600',
  },
  editInput: {
    borderColor: 'rgba(255,255,255,0.3)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.white,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  editBioInput: {
    borderColor: 'rgba(255,255,255,0.3)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 110,
    color: colors.white,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  editActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 12,
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  onboardingScrollView: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#f8fafc',
  },
  onboardingCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  onboardingTitle: {
    color: '#0f172a',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 8,
  },
  onboardingSubtitle: {
    color: '#475569',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 18,
  },
  avatarPreview: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#dbeafe',
  },
  avatarPlaceholder: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#bfdbfe',
  },
  avatarPlaceholderText: {
    color: '#2563eb',
    fontWeight: '600',
  },
  profileScrollView: {
    flexGrow: 1,
    padding: 20,
    paddingTop: 40,
    paddingBottom: 100,
    backgroundColor: colors.darkBlue,
  },
  profileCard: {
    backgroundColor: colors.mediumBlue,
    borderRadius: 24,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  profilePhoto: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignSelf: 'center',
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  profilePhotoPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignSelf: 'center',
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilePhotoPlaceholderText: {
    color: colors.white,
    fontWeight: '600',
  },
  profileName: {
    color: colors.white,
    fontSize: 24,
    fontFamily: 'Marcellus_400Regular',
    textAlign: 'center',
    marginBottom: 4,
  },
  profileEmail: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
  },
  profileInfoBlock: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.2)',
    paddingTop: 14,
    marginBottom: 14,
  },
  profileLabel: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  profileValue: {
    color: colors.white,
    fontSize: 16,
    lineHeight: 22,
  },
  fieldLabel: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  bioInput: {
    borderColor: '#cbd5e1',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 110,
  },
  linkButton: {
    marginTop: 10,
  },
  linkText: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    marginBottom: 8,
  },
  successContainer: {
    alignItems: 'center',
  },
  navigationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    bottom: 20,
    left: '7%',
    right: '7%',
    padding: 10,
    borderRadius: 40,
    backgroundColor: colors.mediumBlue,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
  },
  navigationItem: {
    flex: 1,
    marginHorizontal: 2,
    borderRadius: 30,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  navigationItemActive: {
    backgroundColor: colors.darkBlue,
  },
  navigationLabel: {
    fontFamily: 'Marcellus_400Regular',
    fontSize: 12,
    color: '#bfdbfe',
  },
  navigationLabelActive: {
    color: colors.white,
  },
});