import { StyleSheet } from 'react-native';

export const colors = {
  darkBlue: '#095389',
  mediumBlue: '#1376BE',
  pending: '#FF7052',
  pendingLight: '#FFBEB5',
  awaiting: '#FFA852',
  awaitingLight: '#FFF1A1',
  confirmed: '#37B157',
  confirmedLight: '#B9FFB0',
  white: '#FFFFFF',
};

export default StyleSheet.create({
  // App-specific
  screen: { flex: 1, backgroundColor: colors.darkBlue, justifyContent: 'center', padding: 24 },
  card: { backgroundColor: colors.white, borderRadius: 24, padding: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 16, elevation: 4 },
  title: { fontFamily: 'Marcellus_400Regular', fontSize: 32, color: colors.darkBlue, marginBottom: 8 },
  subtitle: { fontFamily: 'Marcellus_400Regular', fontSize: 16, color: colors.darkBlue, marginBottom: 20 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 15, backgroundColor: colors.darkBlue },
  headerText: { fontFamily: 'Marcellus_400Regular', fontSize: 14, color: colors.white },
  logoutText: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 14 },
  contentContainer: { flex: 1 },
  appContainer: {
    flex: 1,
    backgroundColor: colors.darkBlue,
  },
  pageScreen: {
    flex: 1,
    backgroundColor: colors.darkBlue,
    justifyContent: 'center',
    paddingTop: 40,
    paddingHorizontal: 24,
    paddingBottom: 100,
  },
  pageTitle: {
    fontSize: 38,
    fontWeight: '800',
    color: colors.darkBlue,
    marginBottom: 12,
  },
  pageSubtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.darkBlue,
  },
  pageCard: {
    flex: 1,
    borderRadius: 28,
    backgroundColor: colors.white,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 6,
  },
  calendarScreen: {
    padding: 20,
    paddingBottom: 28,
    backgroundColor: colors.darkBlue,
  },
  calendarHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  calendarTitle: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 31 },
  visibilityButton: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(112, 190, 239, 0.34)' },
  visibilityIcon: { color: '#fff', fontSize: 23 },
  monthControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28 },
  monthButton: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(112, 190, 239, 0.38)' },
  monthButtonText: { color: '#fff', fontSize: 28, lineHeight: 30 },
  monthTitle: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 20 },
  calendarCard: { borderRadius: 25, padding: 12, backgroundColor: colors.mediumBlue },
  weekdayRow: { flexDirection: 'row', marginBottom: 6 },
  weekday: { flex: 1, color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 13, textAlign: 'center', opacity: 0.72 },
  daysGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: { width: '14.2857%', height: 62, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  selectedDay: { backgroundColor: 'rgba(145, 211, 249, 0.68)' },
  todayDay: { backgroundColor: colors.darkBlue },
  dayText: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 15 },
  outsideMonthText: { color: 'rgba(255,255,255,0.35)' },
  dotRow: { flexDirection: 'row', minHeight: 8, marginTop: 3 },
  dayDot: { width: 5, height: 5, borderRadius: 3, marginHorizontal: 2 },
  ridesHeadingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 26, marginBottom: 12 },
  ridesHeading: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 20 },
  rideCard: { borderLeftWidth: 10, borderRadius: 20, padding: 14, marginBottom: 12, backgroundColor: colors.mediumBlue },
  rideTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
  rideStatus: { flex: 1, color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 13 },
  rideTime: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 12, textAlign: 'right' },
  rideDetail: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 14, marginBottom: 6 },
  rideDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.28)', marginVertical: 4 },
  driverName: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 14, marginTop: 4 },
  vehicleText: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 12, opacity: 0.78 },
  seeMoreLink: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, marginTop: 10 },
  seeMoreLinkText: { color: colors.white, fontSize: 12, fontWeight: '600', opacity: 0.85 },
  emptyRides: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 15, marginBottom: 22, opacity: 0.72 },
  newRideButton: { alignSelf: 'flex-end', flexDirection: 'row', alignItems: 'center', borderRadius: 28, paddingVertical: 12, paddingHorizontal: 18, backgroundColor: colors.mediumBlue, elevation: 5 },
  newRidePlus: { color: '#fff', fontSize: 28, lineHeight: 28, marginRight: 7 },
  newRideText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  loadingScreen: {
    flex: 1,
    backgroundColor: colors.darkBlue,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    color: colors.white,
    fontSize: 15,
    marginTop: 12,
  },
  input: {
    borderColor: '#cbd5e1',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2563eb',
    borderRadius: 12,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  primaryButtonDisabled: {
    backgroundColor: '#93c5fd',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  helperText: {
    color: '#64748b',
    fontSize: 13,
    marginTop: 12,
    textAlign: 'center',
  },
  editButton: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 12,
  },
  editButtonText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  avatarUploadButton: {
    alignSelf: 'center',
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
    borderRadius: 999,
    borderWidth: 1,
    marginBottom: 14,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  avatarUploadText: {
    color: '#1d4ed8',
    fontWeight: '600',
  },
  editInput: {
    borderColor: 'rgba(255,255,255,0.3)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.white,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  editBioInput: {
    borderColor: 'rgba(255,255,255,0.3)',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 110,
    color: colors.white,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  editActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 8,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 12,
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: colors.pending,
    borderRadius: 12,
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dangerButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  successButton: {
    alignItems: 'center',
    backgroundColor: colors.confirmed,
    borderRadius: 12,
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  successButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  onboardingScrollView: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#f8fafc',
  },
  onboardingCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  onboardingTitle: {
    color: '#0f172a',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 8,
  },
  onboardingSubtitle: {
    color: '#475569',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 18,
  },
  avatarPreview: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#dbeafe',
  },
  avatarPlaceholder: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#bfdbfe',
  },
  avatarPlaceholderText: {
    color: '#2563eb',
    fontWeight: '600',
  },
  profileScrollView: {
    flexGrow: 1,
    padding: 20,
    paddingTop: 40,
    paddingBottom: 100,
    backgroundColor: colors.darkBlue,
  },
  profileCard: {
    backgroundColor: colors.mediumBlue,
    borderRadius: 24,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  profilePhoto: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignSelf: 'center',
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  profilePhotoPlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignSelf: 'center',
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilePhotoPlaceholderText: {
    color: colors.white,
    fontWeight: '600',
  },
  profileName: {
    color: colors.white,
    fontSize: 24,
    fontFamily: 'Marcellus_400Regular',
    textAlign: 'center',
    marginBottom: 4,
  },
  profileEmail: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
  },
  profileInfoBlock: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.2)',
    paddingTop: 14,
    marginBottom: 14,
  },
  profileLabel: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  profileValue: {
    color: colors.white,
    fontSize: 16,
    lineHeight: 22,
  },
  fieldLabel: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  bioInput: {
    borderColor: '#cbd5e1',
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 110,
  },
  linkButton: {
    marginTop: 10,
  },
  linkText: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    marginBottom: 8,
  },
  successContainer: {
    alignItems: 'center',
  },
  navigationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    bottom: 20,
    left: '7%',
    right: '7%',
    padding: 10,
    borderRadius: 40,
    backgroundColor: colors.mediumBlue,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
  },
  navigationItem: {
    flex: 1,
    marginHorizontal: 2,
    borderRadius: 30,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  navigationItemActive: {
    backgroundColor: colors.darkBlue,
  },
  navigationLabel: {
    fontFamily: 'Marcellus_400Regular',
    fontSize: 12,
    color: '#bfdbfe',
  },
  navigationLabelActive: {
    color: colors.white,
  },
  detailScreen: { padding: 20, paddingBottom: 34, backgroundColor: colors.darkBlue },
  backButton: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', marginBottom: 14, paddingVertical: 4 },
  backButtonText: { color: colors.white, fontSize: 42, lineHeight: 42, marginRight: 8 },
  backButtonLabel: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 20 },
  detailTitle: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 31 },
  detailDate: { color: colors.white, opacity: 0.72, fontFamily: 'Marcellus_400Regular', fontSize: 14, marginTop: 5, marginBottom: 18 },
  detailStatusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  detailTime: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 20 },
  statusPill: { borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7 },
  statusPillText: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 12 },
  mapPreview: { height: 190, borderRadius: 22, overflow: 'hidden', backgroundColor: '#8FC5B1', position: 'relative', marginBottom: 16 },
  mapRoadOne: { position: 'absolute', width: '120%', height: 18, top: 72, left: -22, backgroundColor: '#E7E1C8', transform: [{ rotate: '-18deg' }] },
  mapRoadTwo: { position: 'absolute', width: '120%', height: 13, top: 128, left: -10, backgroundColor: '#E7E1C8', transform: [{ rotate: '24deg' }] },
  mapRoadThree: { position: 'absolute', width: 14, height: '120%', top: -14, left: '64%', backgroundColor: '#E7E1C8', transform: [{ rotate: '28deg' }] },
  mapRoute: { position: 'absolute', width: '31%', height: 5, top: 104, left: '29%', backgroundColor: colors.mediumBlue, transform: [{ rotate: '-22deg' }] },
  mapRouteAlternate: { top: 67, left: '49%', transform: [{ rotate: '-28deg' }] },
  mapMarker: { position: 'absolute', width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: colors.white, backgroundColor: colors.mediumBlue },
  mapStopMarker: { backgroundColor: colors.awaiting },
  mapDropoffMarker: { top: 38, right: '16%', backgroundColor: colors.pending },
  mapMarkerText: { color: colors.white, fontWeight: '800', fontSize: 13 },
  mapCaption: { position: 'absolute', left: 10, bottom: 10, borderRadius: 12, paddingHorizontal: 9, paddingVertical: 6, backgroundColor: 'rgba(9,83,137,0.84)' },
  mapCaptionText: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 11 },
  detailSection: { borderRadius: 20, padding: 16, marginBottom: 12, backgroundColor: colors.mediumBlue },
  detailSectionTitle: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 17, marginBottom: 14 },
  locationRow: { flexDirection: 'row', alignItems: 'flex-start' },
  locationDot: { fontSize: 18, marginRight: 12, lineHeight: 22 },
  locationLabel: { color: colors.white, opacity: 0.68, fontFamily: 'Marcellus_400Regular', fontSize: 12 },
  locationText: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 15, marginTop: 2 },
  locationMeta: { color: colors.white, opacity: 0.7, fontFamily: 'Marcellus_400Regular', fontSize: 12, marginTop: 3 },
  locationLine: { width: 1, height: 17, marginLeft: 8, backgroundColor: 'rgba(255,255,255,0.35)' },
  personRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 13 },
  avatar: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.confirmedLight },
  avatarText: { color: colors.darkBlue, fontFamily: 'Marcellus_400Regular', fontSize: 15 },
  personCopy: { flex: 1, marginLeft: 12 },
  personName: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 15 },
  personBio: { color: colors.white, opacity: 0.72, fontFamily: 'Marcellus_400Regular', fontSize: 12, lineHeight: 17, marginTop: 3 },
  infoLine: { color: colors.white, opacity: 0.8, fontFamily: 'Marcellus_400Regular', fontSize: 12, lineHeight: 20 },
  mutedDetail: { color: colors.white, opacity: 0.7, fontFamily: 'Marcellus_400Regular', fontSize: 13, lineHeight: 19 },
  carRow: { flexDirection: 'row', alignItems: 'center' },
  carIcon: { color: colors.confirmedLight, fontSize: 30, marginRight: 13 },
  savingsPanel: { borderRadius: 20, padding: 18, marginBottom: 12, backgroundColor: colors.confirmed },
  savingsKicker: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 11, letterSpacing: 1 },
  savingsValue: { color: colors.white, fontFamily: 'Marcellus_400Regular', fontSize: 25, marginTop: 5 },
  savingsText: { color: colors.white, opacity: 0.9, fontFamily: 'Marcellus_400Regular', fontSize: 12, marginTop: 5 },
  costPanel: { borderRadius: 20, padding: 18, backgroundColor: colors.white },
  costTitle: { color: colors.darkBlue, fontFamily: 'Marcellus_400Regular', fontSize: 17, marginBottom: 12 },
  costRow: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#D9E7EE', paddingVertical: 8 },
  costLabel: { color: colors.darkBlue, fontFamily: 'Marcellus_400Regular', fontSize: 13 },
  costValue: { color: colors.darkBlue, fontFamily: 'Marcellus_400Regular', fontSize: 14 },
  costNote: { color: colors.darkBlue, opacity: 0.62, fontFamily: 'Marcellus_400Regular', fontSize: 11, marginTop: 12 },
});