// this file was generated by copilot and reviewed by a human

export const launchImageLibraryAsync = async (options: any) => {
  await new Promise(r => setTimeout(r, 5));

  // Simulate user cancel
  if (options?.simulateCancel) {
    return { cancelled: true };
  }

  // Simulate successful image selection
  return {
    cancelled: false,
    assets: [
      {
        uri: "mock://image.jpg",
        width: 800,
        height: 600,
        type: "image",
        fileName: "image.jpg"
      }
    ]
  };
};

export const launchCameraAsync = async (options: any) => {
  await new Promise(r => setTimeout(r, 5));

  if (options?.simulateCancel) {
    return { cancelled: true };
  }

  return {
    cancelled: false,
    assets: [
      {
        uri: "mock://camera-image.jpg",
        width: 1024,
        height: 768,
        type: "image",
        fileName: "camera-image.jpg"
      }
    ]
  };
};

// Reset between tests (if needed)
export const __resetImagePickerMock = () => { };
