// this file was generated by copilot and reviewed by a human

const FIRESTORE_ID_REGEX = /^[A-Za-z0-9]{16,20}$/;

module.exports = {
  test(value) {
    // Only serialize objects containing Firestore-like IDs
    return (
      value &&
      typeof value === "object" &&
      typeof value.id === "string" &&
      FIRESTORE_ID_REGEX.test(value.id)
    );
  },

  print(value, serialize) {
    // Replace the random ID with a stable placeholder
    const stable = {
      ...value,
      id: "<FirestoreID>"
    };

    return serialize(stable);
  }
};
