// this file was generated by copilot and reviewed by a human

let currentUser: any = null;

export const getAuth = () => ({
  currentUser,
});

export const signInWithEmailAndPassword = async (_auth: any, email: string, password: string) => {
  await new Promise(r => setTimeout(r, 5));

  if (email === "error@example.com") {
    throw { code: "auth/invalid-credentials", message: "Invalid credentials" };
  }

  currentUser = {
    uid: "mockUser123",
    email,
    password,
  };

  return { user: currentUser };
};

export const signOut = async () => {
  await new Promise(r => setTimeout(r, 5));
  currentUser = null;
};

export const onAuthStateChanged = (auth: any, callback: (user: any) => void) => {
  callback(auth.currentUser);
  return () => { };
};

// Reset between tests
export const __resetAuthMock = () => {
  currentUser = null;
};
