// this file was generated by copilot and reviewed by a human

// In-memory mock database
let mockDb: Record<string, Record<string, any>> = {};

// Utility: generate Firestore-like IDs
const generateId = () =>
    Math.random().toString(36).substring(2, 12) +
    Math.random().toString(36).substring(2, 12);

// Firestore API mocks
export const getFirestore = () => ({});

// Timestamp (mirrors the fromDate/toDate surface firebase/firestore exposes)
export class Timestamp {
    private constructor(private readonly _date: Date) { }

    static fromDate(date: Date): Timestamp {
        return new Timestamp(date);
    }

    toDate(): Date {
        return this._date;
    }
}

// Collection reference
export const collection = (_db: any, name: string) => ({
    __type: "collection",
    name,
});

// Document reference
export const doc = (_db: any, collectionName: string, id: string) => ({
    __type: "doc",
    collectionName,
    id,
});

// getDoc
export const getDoc = async (docRef: any) => {
    await new Promise(r => setTimeout(r, 5));

    const col = mockDb[docRef.collectionName] || {};
    const data = col[docRef.id];

    return {
        exists: () => !!data,
        id: docRef.id,
        data: () => data || null,
    };
};

// getDocs (for queries or full collection)
export const getDocs = async (queryRef: any) => {
    await new Promise(r => setTimeout(r, 5));

    const col = mockDb[queryRef.collectionName] || {};

    let docs = Object.entries(col).map(([id, data]) => ({
        id,
        data: () => data,
    }));

    // Apply filters
    for (const filter of queryRef.__filters || []) {
        const { field, op, value } = filter;

        if (op === "==") {
            docs = docs.filter(d => d.data()[field] === value);
        }
    }

    return {
        docs,
        size: docs.length,
    };
};

// setDoc
export const setDoc = async (docRef: any, data: any) => {
    await new Promise(r => setTimeout(r, 5));

    if (!mockDb[docRef.collectionName]) {
        mockDb[docRef.collectionName] = {};
    }

    mockDb[docRef.collectionName][docRef.id] = data;
};

// deleteField - a sentinel that updates remove the field for, as Firestore does
const DELETE_FIELD = Symbol("deleteField");
export const deleteField = () => DELETE_FIELD;

// updateDoc
export const updateDoc = async (docRef: any, data: any) => {
    await new Promise(r => setTimeout(r, 5));

    if (!mockDb[docRef.collectionName]?.[docRef.id]) {
        throw { code: "not-found", message: "Document does not exist" };
    }

    const merged = { ...mockDb[docRef.collectionName][docRef.id], ...data };
    for (const [field, value] of Object.entries(data)) {
        if (value === DELETE_FIELD) delete merged[field];
    }
    mockDb[docRef.collectionName][docRef.id] = merged;
};

// runTransaction - reads go straight through; updates are buffered and applied
// only once the callback succeeds, so a throw inside it writes nothing (no
// retries or contention, unlike the real thing)
export const runTransaction = async (_db: any, fn: (tx: any) => Promise<any>) => {
    const writes: Array<[any, any]> = [];
    const tx = {
        get: (docRef: any) => getDoc(docRef),
        update: (docRef: any, data: any) => { writes.push([docRef, data]); return tx; },
    };
    const result = await fn(tx);
    for (const [docRef, data] of writes) await updateDoc(docRef, data);
    return result;
};

// addDoc
export const addDoc = async (collectionRef: any, data: any) => {
    await new Promise(r => setTimeout(r, 5));

    const id = generateId();

    if (!mockDb[collectionRef.name]) {
        mockDb[collectionRef.name] = {};
    }

    mockDb[collectionRef.name][id] = data;

    return {
        id,
        collectionName: collectionRef.name,
    };
};

// deleteDoc
export const deleteDoc = async (docRef: any) => {
    await new Promise(r => setTimeout(r, 5));

    delete mockDb[docRef.collectionName]?.[docRef.id];
};

// Query builder
export const query = (collectionRef: any, ...filters: any[]) => ({
    __type: "query",
    collectionName: collectionRef.name,
    __filters: filters,
});

// where
export const where = (field: string, op: string, value: any) => ({
    field,
    op,
    value,
});

// Reset between tests
export const __resetFirestoreMock = () => {
    mockDb = {};
};
