// this file was generated by copilot and reviewed by a human

let store: Record<string, string> = {};

const AsyncStorage = {
  setItem: async (key: string, value: string) => {
    await new Promise(r => setTimeout(r, 1));
    store[key] = value;
  },

  getItem: async (key: string) => {
    await new Promise(r => setTimeout(r, 1));
    return store[key] ?? null;
  },

  removeItem: async (key: string) => {
    await new Promise(r => setTimeout(r, 1));
    delete store[key];
  },

  clear: async () => {
    await new Promise(r => setTimeout(r, 1));
    store = {};
  },

  getAllKeys: async () => {
    await new Promise(r => setTimeout(r, 1));
    return Object.keys(store);
  },

  // Reset between tests
  __reset: () => {
    store = {};
  }
};

export default AsyncStorage;
