name: Run CI
run-name: Applying CI to ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches: [ "main", "feat*" ]
  pull_request:
    branches: [ "main", "feat*" ]

jobs:
  test:
    runs-on: [ubuntu-slim, macos-latest]
    strategy:
      matrix:
        node-version: [18.X, 24.X]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npx tsc --noEmit

      - name: Run tests (with coverage)
        run: npm test -- --cverage --ci

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with: 
          name: html-coverage
          path: coverage/lcov-report
